// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/google/wire"
	"github.com/kodaikumatani/grpc-cqrs/internal"
	"github.com/kodaikumatani/grpc-cqrs/internal/app"
	"github.com/kodaikumatani/grpc-cqrs/internal/app/recipe"
	command2 "github.com/kodaikumatani/grpc-cqrs/internal/app/recipe/command"
	query2 "github.com/kodaikumatani/grpc-cqrs/internal/app/recipe/query"
	"github.com/kodaikumatani/grpc-cqrs/internal/db"
	"github.com/kodaikumatani/grpc-cqrs/internal/db/command"
	"github.com/kodaikumatani/grpc-cqrs/internal/db/query"
)

// Injectors from wire.go:

func initializeServices(ctx context.Context, dsn string) (*services, func(), error) {
	pool, cleanup, err := db.NewPool(ctx, dsn)
	if err != nil {
		return nil, nil, err
	}
	storage := command.NewRecipe(pool)
	commandCommand := command2.NewCommand(storage)
	queryStorage := query.NewRecipe(pool)
	queryQuery := query2.NewQuery(queryStorage)
	recipeServiceServer := recipe.NewHandler(commandCommand, queryQuery)
	registrar := app.NewRegistrar(recipeServiceServer)
	mainServices := &services{
		Registrar: registrar,
	}
	return mainServices, func() {
		cleanup()
	}, nil
}

// wire.go:

type services struct {
	*app.Registrar
}

var set = wire.NewSet(internal.Set, wire.Struct(new(services), "*"))
