// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/google/wire"
	"github.com/kodaikumatani/grpc-cqrs/internal"
	"github.com/kodaikumatani/grpc-cqrs/internal/app"
	recipe2 "github.com/kodaikumatani/grpc-cqrs/internal/app/recipe"
	"github.com/kodaikumatani/grpc-cqrs/internal/db"
	"github.com/kodaikumatani/grpc-cqrs/internal/db/recipe"
)

// Injectors from wire.go:

func initializeServices(ctx context.Context, dsn string) (*services, func(), error) {
	pool, cleanup, err := db.NewPool(ctx, dsn)
	if err != nil {
		return nil, nil, err
	}
	storage := recipe.NewRepository(pool)
	useCase := recipe2.NewUseCase(storage)
	handler := recipe2.NewHandler(useCase)
	registrar := app.NewRegistrar(handler)
	mainServices := &services{
		Registrar: registrar,
	}
	return mainServices, func() {
		cleanup()
	}, nil
}

// wire.go:

type services struct {
	*app.Registrar
}

var set = wire.NewSet(internal.Set, wire.Struct(new(services), "*"))
