// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: recipe/recipe.proto

package recipe

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Visibility int32

const (
	Visibility_VISIBILITY_UNSPECIFIED Visibility = 0
	Visibility_VISIBILITY_PUBLIC      Visibility = 1
	Visibility_VISIBILITY_PRIVATE     Visibility = 2
	Visibility_VISIBILITY_RESTRICTED  Visibility = 3
)

// Enum value maps for Visibility.
var (
	Visibility_name = map[int32]string{
		0: "VISIBILITY_UNSPECIFIED",
		1: "VISIBILITY_PUBLIC",
		2: "VISIBILITY_PRIVATE",
		3: "VISIBILITY_RESTRICTED",
	}
	Visibility_value = map[string]int32{
		"VISIBILITY_UNSPECIFIED": 0,
		"VISIBILITY_PUBLIC":      1,
		"VISIBILITY_PRIVATE":     2,
		"VISIBILITY_RESTRICTED":  3,
	}
)

func (x Visibility) Enum() *Visibility {
	p := new(Visibility)
	*p = x
	return p
}

func (x Visibility) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Visibility) Descriptor() protoreflect.EnumDescriptor {
	return file_recipe_recipe_proto_enumTypes[0].Descriptor()
}

func (Visibility) Type() protoreflect.EnumType {
	return &file_recipe_recipe_proto_enumTypes[0]
}

func (x Visibility) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Visibility.Descriptor instead.
func (Visibility) EnumDescriptor() ([]byte, []int) {
	return file_recipe_recipe_proto_rawDescGZIP(), []int{0}
}

type Recipe struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Visibility    Visibility             `protobuf:"varint,7,opt,name=visibility,proto3,enum=recipe.Visibility" json:"visibility,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Recipe) Reset() {
	*x = Recipe{}
	mi := &file_recipe_recipe_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Recipe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Recipe) ProtoMessage() {}

func (x *Recipe) ProtoReflect() protoreflect.Message {
	mi := &file_recipe_recipe_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Recipe.ProtoReflect.Descriptor instead.
func (*Recipe) Descriptor() ([]byte, []int) {
	return file_recipe_recipe_proto_rawDescGZIP(), []int{0}
}

func (x *Recipe) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Recipe) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Recipe) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Recipe) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Recipe) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Recipe) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Recipe) GetVisibility() Visibility {
	if x != nil {
		return x.Visibility
	}
	return Visibility_VISIBILITY_UNSPECIFIED
}

type CreateRecipeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRecipeRequest) Reset() {
	*x = CreateRecipeRequest{}
	mi := &file_recipe_recipe_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRecipeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRecipeRequest) ProtoMessage() {}

func (x *CreateRecipeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recipe_recipe_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRecipeRequest.ProtoReflect.Descriptor instead.
func (*CreateRecipeRequest) Descriptor() ([]byte, []int) {
	return file_recipe_recipe_proto_rawDescGZIP(), []int{1}
}

func (x *CreateRecipeRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateRecipeRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CreateRecipeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RecipeId      string                 `protobuf:"bytes,1,opt,name=recipe_id,json=recipeId,proto3" json:"recipe_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRecipeResponse) Reset() {
	*x = CreateRecipeResponse{}
	mi := &file_recipe_recipe_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRecipeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRecipeResponse) ProtoMessage() {}

func (x *CreateRecipeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_recipe_recipe_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRecipeResponse.ProtoReflect.Descriptor instead.
func (*CreateRecipeResponse) Descriptor() ([]byte, []int) {
	return file_recipe_recipe_proto_rawDescGZIP(), []int{2}
}

func (x *CreateRecipeResponse) GetRecipeId() string {
	if x != nil {
		return x.RecipeId
	}
	return ""
}

type GetRecipeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecipeRequest) Reset() {
	*x = GetRecipeRequest{}
	mi := &file_recipe_recipe_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecipeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecipeRequest) ProtoMessage() {}

func (x *GetRecipeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recipe_recipe_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecipeRequest.ProtoReflect.Descriptor instead.
func (*GetRecipeRequest) Descriptor() ([]byte, []int) {
	return file_recipe_recipe_proto_rawDescGZIP(), []int{3}
}

func (x *GetRecipeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetRecipeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Recipe        *Recipe                `protobuf:"bytes,1,opt,name=recipe,proto3" json:"recipe,omitempty"`
	User          *User                  `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecipeResponse) Reset() {
	*x = GetRecipeResponse{}
	mi := &file_recipe_recipe_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecipeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecipeResponse) ProtoMessage() {}

func (x *GetRecipeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_recipe_recipe_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecipeResponse.ProtoReflect.Descriptor instead.
func (*GetRecipeResponse) Descriptor() ([]byte, []int) {
	return file_recipe_recipe_proto_rawDescGZIP(), []int{4}
}

func (x *GetRecipeResponse) GetRecipe() *Recipe {
	if x != nil {
		return x.Recipe
	}
	return nil
}

func (x *GetRecipeResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_recipe_recipe_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_recipe_recipe_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_recipe_recipe_proto_rawDescGZIP(), []int{5}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type UpdateRecipeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRecipeRequest) Reset() {
	*x = UpdateRecipeRequest{}
	mi := &file_recipe_recipe_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRecipeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRecipeRequest) ProtoMessage() {}

func (x *UpdateRecipeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recipe_recipe_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRecipeRequest.ProtoReflect.Descriptor instead.
func (*UpdateRecipeRequest) Descriptor() ([]byte, []int) {
	return file_recipe_recipe_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateRecipeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateRecipeRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateRecipeRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type UpdateRecipeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRecipeResponse) Reset() {
	*x = UpdateRecipeResponse{}
	mi := &file_recipe_recipe_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRecipeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRecipeResponse) ProtoMessage() {}

func (x *UpdateRecipeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_recipe_recipe_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRecipeResponse.ProtoReflect.Descriptor instead.
func (*UpdateRecipeResponse) Descriptor() ([]byte, []int) {
	return file_recipe_recipe_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateRecipeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ChangeVisibilityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Visibility    Visibility             `protobuf:"varint,2,opt,name=visibility,proto3,enum=recipe.Visibility" json:"visibility,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeVisibilityRequest) Reset() {
	*x = ChangeVisibilityRequest{}
	mi := &file_recipe_recipe_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeVisibilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeVisibilityRequest) ProtoMessage() {}

func (x *ChangeVisibilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recipe_recipe_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeVisibilityRequest.ProtoReflect.Descriptor instead.
func (*ChangeVisibilityRequest) Descriptor() ([]byte, []int) {
	return file_recipe_recipe_proto_rawDescGZIP(), []int{8}
}

func (x *ChangeVisibilityRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChangeVisibilityRequest) GetVisibility() Visibility {
	if x != nil {
		return x.Visibility
	}
	return Visibility_VISIBILITY_UNSPECIFIED
}

type ChangeVisibilityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeVisibilityResponse) Reset() {
	*x = ChangeVisibilityResponse{}
	mi := &file_recipe_recipe_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeVisibilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeVisibilityResponse) ProtoMessage() {}

func (x *ChangeVisibilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_recipe_recipe_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeVisibilityResponse.ProtoReflect.Descriptor instead.
func (*ChangeVisibilityResponse) Descriptor() ([]byte, []int) {
	return file_recipe_recipe_proto_rawDescGZIP(), []int{9}
}

func (x *ChangeVisibilityResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_recipe_recipe_proto protoreflect.FileDescriptor

const file_recipe_recipe_proto_rawDesc = "" +
	"\n" +
	"\x13recipe/recipe.proto\x12\x06recipe\x1a\x1fgoogle/protobuf/timestamp.proto\"\x93\x02\n" +
	"\x06Recipe\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x122\n" +
	"\n" +
	"visibility\x18\a \x01(\x0e2\x12.recipe.VisibilityR\n" +
	"visibility\"M\n" +
	"\x13CreateRecipeRequest\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"3\n" +
	"\x14CreateRecipeResponse\x12\x1b\n" +
	"\trecipe_id\x18\x01 \x01(\tR\brecipeId\"\"\n" +
	"\x10GetRecipeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"]\n" +
	"\x11GetRecipeResponse\x12&\n" +
	"\x06recipe\x18\x01 \x01(\v2\x0e.recipe.RecipeR\x06recipe\x12 \n" +
	"\x04user\x18\x02 \x01(\v2\f.recipe.UserR\x04user\"@\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\"]\n" +
	"\x13UpdateRecipeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"0\n" +
	"\x14UpdateRecipeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"]\n" +
	"\x17ChangeVisibilityRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x122\n" +
	"\n" +
	"visibility\x18\x02 \x01(\x0e2\x12.recipe.VisibilityR\n" +
	"visibility\"4\n" +
	"\x18ChangeVisibilityResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess*r\n" +
	"\n" +
	"Visibility\x12\x1a\n" +
	"\x16VISIBILITY_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11VISIBILITY_PUBLIC\x10\x01\x12\x16\n" +
	"\x12VISIBILITY_PRIVATE\x10\x02\x12\x19\n" +
	"\x15VISIBILITY_RESTRICTED\x10\x032\xbe\x02\n" +
	"\rRecipeService\x12I\n" +
	"\fCreateRecipe\x12\x1b.recipe.CreateRecipeRequest\x1a\x1c.recipe.CreateRecipeResponse\x12@\n" +
	"\tGetRecipe\x12\x18.recipe.GetRecipeRequest\x1a\x19.recipe.GetRecipeResponse\x12I\n" +
	"\fUpdateRecipe\x12\x1b.recipe.UpdateRecipeRequest\x1a\x1c.recipe.UpdateRecipeResponse\x12U\n" +
	"\x10ChangeVisibility\x12\x1f.recipe.ChangeVisibilityRequest\x1a .recipe.ChangeVisibilityResponseB5Z3github.com/kodaikumatani/grpc-cqrs-go/pkg/pb/recipeb\x06proto3"

var (
	file_recipe_recipe_proto_rawDescOnce sync.Once
	file_recipe_recipe_proto_rawDescData []byte
)

func file_recipe_recipe_proto_rawDescGZIP() []byte {
	file_recipe_recipe_proto_rawDescOnce.Do(func() {
		file_recipe_recipe_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_recipe_recipe_proto_rawDesc), len(file_recipe_recipe_proto_rawDesc)))
	})
	return file_recipe_recipe_proto_rawDescData
}

var file_recipe_recipe_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_recipe_recipe_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_recipe_recipe_proto_goTypes = []any{
	(Visibility)(0),                  // 0: recipe.Visibility
	(*Recipe)(nil),                   // 1: recipe.Recipe
	(*CreateRecipeRequest)(nil),      // 2: recipe.CreateRecipeRequest
	(*CreateRecipeResponse)(nil),     // 3: recipe.CreateRecipeResponse
	(*GetRecipeRequest)(nil),         // 4: recipe.GetRecipeRequest
	(*GetRecipeResponse)(nil),        // 5: recipe.GetRecipeResponse
	(*User)(nil),                     // 6: recipe.User
	(*UpdateRecipeRequest)(nil),      // 7: recipe.UpdateRecipeRequest
	(*UpdateRecipeResponse)(nil),     // 8: recipe.UpdateRecipeResponse
	(*ChangeVisibilityRequest)(nil),  // 9: recipe.ChangeVisibilityRequest
	(*ChangeVisibilityResponse)(nil), // 10: recipe.ChangeVisibilityResponse
	(*timestamppb.Timestamp)(nil),    // 11: google.protobuf.Timestamp
}
var file_recipe_recipe_proto_depIdxs = []int32{
	11, // 0: recipe.Recipe.created_at:type_name -> google.protobuf.Timestamp
	11, // 1: recipe.Recipe.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: recipe.Recipe.visibility:type_name -> recipe.Visibility
	1,  // 3: recipe.GetRecipeResponse.recipe:type_name -> recipe.Recipe
	6,  // 4: recipe.GetRecipeResponse.user:type_name -> recipe.User
	0,  // 5: recipe.ChangeVisibilityRequest.visibility:type_name -> recipe.Visibility
	2,  // 6: recipe.RecipeService.CreateRecipe:input_type -> recipe.CreateRecipeRequest
	4,  // 7: recipe.RecipeService.GetRecipe:input_type -> recipe.GetRecipeRequest
	7,  // 8: recipe.RecipeService.UpdateRecipe:input_type -> recipe.UpdateRecipeRequest
	9,  // 9: recipe.RecipeService.ChangeVisibility:input_type -> recipe.ChangeVisibilityRequest
	3,  // 10: recipe.RecipeService.CreateRecipe:output_type -> recipe.CreateRecipeResponse
	5,  // 11: recipe.RecipeService.GetRecipe:output_type -> recipe.GetRecipeResponse
	8,  // 12: recipe.RecipeService.UpdateRecipe:output_type -> recipe.UpdateRecipeResponse
	10, // 13: recipe.RecipeService.ChangeVisibility:output_type -> recipe.ChangeVisibilityResponse
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_recipe_recipe_proto_init() }
func file_recipe_recipe_proto_init() {
	if File_recipe_recipe_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_recipe_recipe_proto_rawDesc), len(file_recipe_recipe_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_recipe_recipe_proto_goTypes,
		DependencyIndexes: file_recipe_recipe_proto_depIdxs,
		EnumInfos:         file_recipe_recipe_proto_enumTypes,
		MessageInfos:      file_recipe_recipe_proto_msgTypes,
	}.Build()
	File_recipe_recipe_proto = out.File
	file_recipe_recipe_proto_goTypes = nil
	file_recipe_recipe_proto_depIdxs = nil
}
