// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: share/share.proto

package share

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShareRecipeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RecipeId      string                 `protobuf:"bytes,1,opt,name=recipe_id,json=recipeId,proto3" json:"recipe_id,omitempty"`
	TargetUserId  string                 `protobuf:"bytes,2,opt,name=target_user_id,json=targetUserId,proto3" json:"target_user_id,omitempty"`
	Relation      string                 `protobuf:"bytes,3,opt,name=relation,proto3" json:"relation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShareRecipeRequest) Reset() {
	*x = ShareRecipeRequest{}
	mi := &file_share_share_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShareRecipeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShareRecipeRequest) ProtoMessage() {}

func (x *ShareRecipeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_share_share_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShareRecipeRequest.ProtoReflect.Descriptor instead.
func (*ShareRecipeRequest) Descriptor() ([]byte, []int) {
	return file_share_share_proto_rawDescGZIP(), []int{0}
}

func (x *ShareRecipeRequest) GetRecipeId() string {
	if x != nil {
		return x.RecipeId
	}
	return ""
}

func (x *ShareRecipeRequest) GetTargetUserId() string {
	if x != nil {
		return x.TargetUserId
	}
	return ""
}

func (x *ShareRecipeRequest) GetRelation() string {
	if x != nil {
		return x.Relation
	}
	return ""
}

var File_share_share_proto protoreflect.FileDescriptor

const file_share_share_proto_rawDesc = "" +
	"\n" +
	"\x11share/share.proto\x12\x05share\x1a\x1bgoogle/protobuf/empty.proto\"s\n" +
	"\x12ShareRecipeRequest\x12\x1b\n" +
	"\trecipe_id\x18\x01 \x01(\tR\brecipeId\x12$\n" +
	"\x0etarget_user_id\x18\x02 \x01(\tR\ftargetUserId\x12\x1a\n" +
	"\brelation\x18\x03 \x01(\tR\brelation2P\n" +
	"\fShareService\x12@\n" +
	"\vShareRecipe\x12\x19.share.ShareRecipeRequest\x1a\x16.google.protobuf.EmptyB4Z2github.com/kodaikumatani/grpc-cqrs-go/pkg/pb/shareb\x06proto3"

var (
	file_share_share_proto_rawDescOnce sync.Once
	file_share_share_proto_rawDescData []byte
)

func file_share_share_proto_rawDescGZIP() []byte {
	file_share_share_proto_rawDescOnce.Do(func() {
		file_share_share_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_share_share_proto_rawDesc), len(file_share_share_proto_rawDesc)))
	})
	return file_share_share_proto_rawDescData
}

var file_share_share_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_share_share_proto_goTypes = []any{
	(*ShareRecipeRequest)(nil), // 0: share.ShareRecipeRequest
	(*emptypb.Empty)(nil),      // 1: google.protobuf.Empty
}
var file_share_share_proto_depIdxs = []int32{
	0, // 0: share.ShareService.ShareRecipe:input_type -> share.ShareRecipeRequest
	1, // 1: share.ShareService.ShareRecipe:output_type -> google.protobuf.Empty
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_share_share_proto_init() }
func file_share_share_proto_init() {
	if File_share_share_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_share_share_proto_rawDesc), len(file_share_share_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_share_share_proto_goTypes,
		DependencyIndexes: file_share_share_proto_depIdxs,
		MessageInfos:      file_share_share_proto_msgTypes,
	}.Build()
	File_share_share_proto = out.File
	file_share_share_proto_goTypes = nil
	file_share_share_proto_depIdxs = nil
}
